version: '3.10'

services:
   web:
       build: .
       command: python manage.py runserver localhost:8000
       ports:
           - 8000:8000
#       networks:
#         - net
       depends_on:
         - db
#         - redis
#         - celery


   db:
       restart: always
       image: postgres:latest
       container_name: db_pstgrs
       volumes:
         - ./data/postgres:/var/lib/postgresql/data
       env_file:
         - configs/db.env
       ports:
         - "5432:5432"
#       networks:
#         - net
#
#   redis:
#       image: "redis:alpine"
#       container_name: redis_
#       command: redis-server
#       ports:
#         - "6379:6379"
#       volumes:
#         - ./data/redis/redis-data:/var/lib/redis
#       environment:
#         - REDIS_REPLICATION_MODE=master
#       networks:
#         - net
#  #
#   celery:
#       build: .
#       container_name: celery_
#       environment:
#         - CELERY_BROKER_URL=redis://redis:6379/
#       command: celery -A testdipl worker -l info
#       depends_on:
#         - redis
#       networks:
#         - net

#networks:
#  net: