# Generated by Django 4.2.7 on 2023-11-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='profiles'),
        ),
    ]
